name: Python and Node.js tests with Allure

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - all
   
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Run autotests
        uses: actions/checkout@v4
      
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Conditional section for Python tests
      - name: Python tests
        if: "github.event.inputs.deployment_target != 'none'"
        run: |
          if [[ ${{ github.event.inputs.deployment_target }} == 'all' ]]; then
            pytest --alluredir=allure-results
          elif [[ ${{ github.event.inputs.deployment_target }} == 'smoke' ]]; then
            pytest -m smoke --alluredir=allure-results
          elif [[ ${{ github.event.inputs.deployment_target }} == 'regression' ]]; then
            pytest -m regression --alluredir=allure-results
          elif [[ ${{ github.event.inputs.deployment_target }} == 'extended' ]]; then
            pytest -m extended --alluredir=allure-results
          fi
        continue-on-error: true
      
      # Conditional section for Node.js setup and execution
      - name: Node.js setup and run
        if: "github.event.inputs.deployment_target != 'none'"
        run: |
          # Example commands to set up Node.js (replace with actual setup commands)
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
      
          # Example Node.js execution (replace with your Node.js commands)
          node main.js
      
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      
      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
          sudo tar -zxvf allure-2.24.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
      
      - name: Add Executor And Categories in Allure Results
        run: cp -r categories.json executor.json allure-results/
      
      - name: Generate report  
        run: allure generate -c allure-results -o allure-report
      
      - name: Save allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 1


